name: BazingaBlocks
main: net.bazingablocks.org.Main
version: 1.0.2
api-version: 1.16
author: Bahhzinga
description: Reward your players for mining!

commands:
  bb:
    permission: bazingablocks.admin
    description: Manage your lucky blocks!